// Generated by CoffeeScript 2.5.1


//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic2tldGNoNC5qcyIsInNvdXJjZVJvb3QiOiIuLiIsInNvdXJjZXMiOlsiY29mZmVlXFxza2V0Y2g0LmNvZmZlZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiIiwic291cmNlc0NvbnRlbnQiOlsiIl19
//# sourceURL=c:\github\2023-012-solidjs-coffee-hyperscript-lab\coffee\sketch4.coffee